### ISSUE TITLE
finds duplicates but won't delete

### ISSUE THREAD

**Issue by NightHawkATL** [Cleanarr/Cleanarr#12]
**Describe the bug**
After scanning, Cleanarr cannot delete files that it found to be duplicates and continuously spins rather than timing out with any error message

**To Reproduce**
1. open the app
2. run the scan
3. find duplicates
4. try to delete
5. no error given

**Expected behavior**
files are deleted that are pre-marked as found duplicates

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox 112.0.2

**Smartphone (please complete the following information):**

**Additional context**

**Comment by joshkay** [comment]
same issue on my end.  getting a 500 error when trying to delete.

**Comment by appiekap653** [comment]
May I ask from where you downloaded and installed this app you are referring to?

I don't want to sound ruth but this repository holds no piece of software that is even close to finished...
To be more precise, it holds just the files that are automatically created on project creation in Visual Studio and a small start of some database classes.

The project isn't really started further due to severe health issues that were found out right after the repository creation.

In the meantime I have provided minor help with an other app that has the same goal: https://github.com/jorenn92/Maintainerr , also referred to here #14 .

Could it be that you have installed some other app, which you thought came from this repository?

> Steps to reproduce the behavior:
>
> 1. open the app
> 2. run the scan
> 3. find duplicates
> 4. try to delete

This is not possible with the current state of the code.
There exists no code to represent some scan.
Let alone find something and trying to initiate a delete.
